### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by mdogan** [HdrHistogram/hdrhistogram-go#49]
After upgrading to `v1.1.2`, occasionally we are observing the following panic:

```
panic: runtime error: index out of range [25600] with length 25600
github.com/HdrHistogram/hdrhistogram-go.(*Histogram).getCountAtIndexGivenBucketBaseIdx(...)
	/go/pkg/mod/github.com/!hdr!histogram/hdrhistogram-go@v1.1.2/hdr.go:599
github.com/HdrHistogram/hdrhistogram-go.(*Histogram).getValueFromIdxUpToCount(0xb7, 0x3ff800000)
	/go/pkg/mod/github.com/!hdr!histogram/hdrhistogram-go@v1.1.2/hdr.go:361 +0xb7
github.com/HdrHistogram/hdrhistogram-go.(*Histogram).ValueAtPercentile(0xc0000b6480, 0x0)
	/go/pkg/mod/github.com/!hdr!histogram/hdrhistogram-go@v1.1.2/hdr.go:335 +0x65
github.com/HdrHistogram/hdrhistogram-go.(*Histogram).ValueAtQuantile(...)
	/go/pkg/mod/github.com/!hdr!histogram/hdrhistogram-go@v1.1.2/hdr.go:319
```

Histogram is created with:
```go
hdrhistogram.NewWindowed(windowCount, 1, maxLatency.Nanoseconds(), 3)
```

`WindowedHistogram` is being rotated on every 10mins and `Histogram.ValueAtQuantile()` is called on a `Histogram` produced by `WindowedHistogram.Merge()`.

This panic happened twice in the last ten days. But I'm not able to reproduce it on a local environment. This application is running on production more than a year and we haven't seen this issue with earlier versions.

**Comment by filipecosta90** [comment]
Hi there @mdogan , during the weekend I'll work on extending the tests to try to reach this state ( edge case ). I will keep you posted.  

Just a safe check:
> After upgrading to v1.1.2

The version you had before was v1.1.1 ?

**Comment by mdogan** [comment]
Thanks @filipecosta90.

Actually no. It was v1.1.0 before v1.1.2.

**Comment by stefanv5** [comment]
we also met this panic. we use v1.1.2 
```go
panic: runtime error: index out of range [25600] with length 25600
goroutine 212 [running]:
github.com/HdrHistogram/hdrhistogram-go.(*Histogram).getCountAtIndexGivenBucketBaseIdx(...)
        /root/gopath/pkg/mod/github.com/!hdr!histogram/hdrhistogram-go@v1.1.2/hdr.go:599
github.com/HdrHistogram/hdrhistogram-go.(*Histogram).getValueFromIdxUpToCount(0x1d?, 0xc08fbaa200?)
        /root/gopath/pkg/mod/github.com/!hdr!histogram/hdrhistogram-go@v1.1.2/hdr.go:361 +0xb7
github.com/HdrHistogram/hdrhistogram-go.(*Histogram).ValueAtPercentile(0xc05b2fe200, 0x9?)
        /root/gopath/pkg/mod/github.com/!hdr!histogram/hdrhistogram-go@v1.1.2/hdr.go:335 +0x65
```

**Comment by filipecosta90** [comment]
@stefanv5 do you have an easy reproduction of the bug?

**Comment by stefanv5** [comment]
> @stefanv5 do you have an easy reproduction of the bug?
Thanks for your reply.
In our case, we create 4 goroutines to store monitoring metrics,  and every 10 seconds we calculate metrics' P99 values, then we reset the histogram, we ensure all procedures are atomic. 
Perhaps after 1h, we find panic occurred.
Hope these infomation is helpful.

**Comment by ItsLifeJim** [comment]
We have the same problem - likely related to getting 99.9999 centile.  I think workaround is to use ValueAtPercentiles as it iterates all the buckets and looks to check range (if i.bucketIdx >= i.h.bucketCount) whereas getValueFromIdxUpToCount relies on maths to prevent range overflow and this is what looks to be broken.

**Comment by fcostaoliveira** [comment]
Status check against current `master`:

**The exact panic can no longer occur** — `getCountAtIndexGivenBucketBaseIdx` (the function in the reported stack, `hdr.go:599` in v1.1.2) was removed when the percentile read path was rewritten as a flat `counts[]` scan (#57). So that specific `index out of range` frame is gone.

**But the root cause looks unaddressed.** The report's pattern is `WindowedHistogram.Rotate()` firing on a timer while another goroutine records into / `Merge()`s the histogram. `Rotate()` reassigns `w.Current` and calls `.Reset()` with no synchronization (`window.go:43-44`), and the base `Histogram` isn't safe for concurrent `RecordValue`/read either (no locks/atomics anywhere). Under `go test -race` this is a genuine data race, which can corrupt `totalCount`/`counts[]` and surface as a panic somewhere else in the read path — consistent with 'happens rarely in production, not reproducible locally'.

So I'd suggest **not closing this as fixed**. Two concrete follow-ups:
1. Document that `Histogram`/`WindowedHistogram` are not safe for concurrent use (they currently say nothing), and
2. Make `WindowedHistogram.Rotate()` safe (e.g. atomic `Current` swap + synchronized reset, or swap in a fresh histogram) for the timer-rotation use case this issue describes.

(Context: a `go test -race` CI job is added in #65, which would catch regressions here.)

**Comment by mdogan** [comment]
About concurrent usage, in our case, access was (and still is) synchronized externally. We are still using v1.1.1.
